// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwvgcmogotswxdctpzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d3ZnY21vZ290c3d4ZGN0cHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDI5MjgsImV4cCI6MjA4OTI3ODkyOH0.35uvbwqK1Zv9aSdq3IMGN0CqIBABpn6zG9ZdPuirh8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});